version: '3.8'

services:
  # Служба для базы данных MariaDB
  db:
    image: mariadb:latest
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  # Служба для PHP-FPM
  php:
    image: wordpress:6-php8.3-fpm
    container_name: wordpress_php
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspassword
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network

  # Служба для Nginx
  nginx:
    image: nginx:latest
    container_name: wordpress_nginx
    restart: always
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_status.conf:/etc/nginx/conf.d/status.conf:ro
    networks:
      - wordpress_network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - wordpress_network

  # Node Exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - wordpress_network

  # Nginx Exporter
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    restart: always
    command:
      - "-nginx.scrape-uri=http://nginx:8080/stub_status"
    ports:
      - "9113:9113"
    networks:
      - wordpress_network

  # MySQL Exporter
  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "wordpress:wordpresspassword@(db:3306)/"
    ports:
      - "9104:9104"
    networks:
      - wordpress_network

volumes:
  db_data:
  wordpress_data:

networks:
  wordpress_network:
