version: '3.8'

services:
  # Служба для базы данных MariaDB
  db:
    image: mariadb:latest
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  # Служба для PHP-FPM
  php:
    image: wordpress:6-php8.3-fpm
    container_name: wordpress_php
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspassword
    volumes:
      - wordpress_data:/var/www/html
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/custom.conf:ro
    networks:
      - wordpress_network

  # Служба для Nginx
  nginx:
    image: nginx:latest
    container_name: wordpress_nginx
    restart: always
    depends_on:
      - php
    ports:
      - "80:80"     # Основной порт для WordPress
      - "8081:8081"   # Порт для мониторинга
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_status.conf:/etc/nginx/conf.d/status.conf:ro
      - ./nginx_metrics.conf:/etc/nginx/metrics.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
      - ./cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./key.pem:/etc/nginx/ssl/key.pem:ro
    networks:
      - wordpress_network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=2d'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - wordpress_network

  # Node Exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    networks:
      - wordpress_network

  # Nginx Exporter
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    restart: always
    command:
      - "-nginx.scrape-uri=http://nginx:8080/stub_status"
    networks:
      - wordpress_network

  # MySQL Exporter
  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql_exporter
    restart: always
    volumes:
      - ./.my.cnf:/.my.cnf:ro
    networks:
      - wordpress_network

  # PHP-FPM Exporter
  php-fpm-exporter:
    image: hipages/php-fpm_exporter:latest
    container_name: php_fpm_exporter
    restart: always
    environment:
      PHP_FPM_SCRAPE_URI: "tcp://php:9000/status"
    networks:
      - wordpress_network

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    restart: always
    volumes:
    - ./blackbox.yml:/etc/blackbox_exporter/blackbox.yml:ro
    networks:
    - wordpress_network

  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.115.0
    container_name: victoria_metrics
    restart: always
    ports:
      - "8428:8428"
    command:
      - "--storageDataPath=/storage"
      - "--retentionPeriod=2w"
    volumes:
      - victoria_metrics_data:/storage
    networks:
      - wordpress_network

volumes:
  db_data:
  wordpress_data:
  victoria_metrics_data:
  prometheus_data:

networks:
  wordpress_network:
