global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'php_fpm_exporter'
    static_configs:
      - targets: ['php_fpm_exporter:9253']

  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['mysql_exporter:9104']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Используемый модуль из blackbox.yml
    static_configs:
      - targets:
          - http://localhost  # Адрес для проверки
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # Адрес Blackbox Exporter