global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics/prometheus
    scheme: https
    basic_auth:
      username: 'prometheus_user'
      password: 'eVrIQpGoPhZArqYRV7nJ'
    static_configs:
      - targets: ['nginx:8081']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'node_exporter'
    metrics_path: /metrics/node
    scheme: https
    basic_auth:
      username: 'prometheus_user'
      password: 'eVrIQpGoPhZArqYRV7nJ'
    static_configs:
      - targets: ['nginx:8081']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'nginx_exporter'
    metrics_path: /metrics/nginx
    scheme: https
    basic_auth:
      username: 'prometheus_user'
      password: 'eVrIQpGoPhZArqYRV7nJ'
    static_configs:
      - targets: ['nginx:8081']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'php_fpm_exporter'
    metrics_path: /metrics/php
    scheme: https
    basic_auth:
      username: 'prometheus_user'
      password: 'eVrIQpGoPhZArqYRV7nJ'
    static_configs:
      - targets: ['nginx:8081']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'mysql_exporter'
    metrics_path: /metrics/mysql
    scheme: https
    basic_auth:
      username: 'prometheus_user'
      password: 'eVrIQpGoPhZArqYRV7nJ'
    static_configs:
      - targets: ['nginx:8081']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'blackbox'
    metrics_path: /probe
    scheme: https
    basic_auth:
      username: 'prometheus_user'
      password: 'eVrIQpGoPhZArqYRV7nJ'
    params:
      module: [http_2xx]  # Используемый модуль из blackbox.yml
    static_configs:
      - targets:
          - http://nginx  # Адрес для проверки
    tls_config:
      insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: nginx:8081  # Адрес Blackbox Exporter